### ISSUE TITLE
Develop Music Utilities for Audio (music) State Management

### ISSUE THREAD

**Issue by meganindya** [sugarlabs/musicblocks-v4#106]
_This is a master issue to keep track of objectives via other issues._

Like in Music Blocks v3, utilities are required to manage the audio (musical) states. The implementation will be different though. Establishment, maintenance, and management of the audio states will be encapsulated. The classes built shall be used by a module called the Context Manager to interface with the remainder of the syntax framework.

## Objectives:

- [x] **Develop a prototype**
- [x] [**Appropriately port them**](https://github.com/sugarlabs/musicblocks-v4-lib/issues/18)
- [x] [**Add exhaustive unit tests**](https://github.com/sugarlabs/musicblocks-v4-lib/issues/25)
- [x] [**Add documentation**](https://github.com/sugarlabs/musicblocks-v4-lib/issues/30)
- [x] **Review and Reorganize** sugarlabs/musicblocks-v4-lib#62

All development is done on the [`musicutils`](https://github.com/sugarlabs/musicblocks-v4-lib/tree/musicutils) branch, which shall be merged after completion of this issue.

A project [Develop Music Utilities](https://github.com/sugarlabs/musicblocks-v4-lib/projects/1) has been created to track the progress.
