### ISSUE TITLE
Add TypeScript targeting README for musicutils

### ISSUE THREAD

**Issue by meganindya** [sugarlabs/musicblocks-v4#107]
On branch [`musicutils`](https://github.com/sugarlabs/musicblocks-v4-lib/tree/musicutils), the music utilities are described in [`src/.prototype/musicutils/README.md`](https://github.com/sugarlabs/musicblocks-v4-lib/blob/musicutils/src/.prototype/musicutils/README.md). However, that targets the prototype code written in _Python_.

As the _Python_ files are ported to _TypeScript_, the `README` needs to be updated accordingly. The file has 6 sections; update them based on the current `README` and the new `.ts` files in the [`src/.prototype/musicutils/ts/`](https://github.com/sugarlabs/musicblocks-v4-lib/tree/musicutils/src/.prototype/musicutils/ts) directory.

The sections are:

- [x] `Current Pitch` sugarlabs/musicblocks-v4-lib#48
- [x] `Temperament` sugarlabs/musicblocks-v4-lib#31
- [x] `Key Signature` sugarlabs/musicblocks-v4-lib#54
- [x] `Scale` sugarlabs/musicblocks-v4-lib#50
- [x] `Music Utils` sugarlabs/musicblocks-v4-lib#49
- [x] `Example` sugarlabs/musicblocks-v4-lib#53

Create a new file `README.md` inside the `ts` directory.

Depends on sugarlabs/musicblocks-v4-lib#18.
