### ISSUE TITLE
Add remaining test cases for TypeScript ported files in musicutils

### ISSUE THREAD

**Issue by meganindya** [sugarlabs/musicblocks-v4#108]
On branch [`musicutils`](https://github.com/sugarlabs/musicblocks-v4-lib/tree/musicutils), there are `.test.ts` files corresponding to Python to TypeScript ported files.

However, the test cases aren't exhaustive &mdash; some cases aren't covered. Add missing test cases.

- [x] `scale.test.ts` sugarlabs/musicblocks-v4-lib#41
- [x] `musicUtils.test.ts` sugarlabs/musicblocks-v4-lib#29
- [x] `temperament.test.ts` sugarlabs/musicblocks-v4-lib#37
- [x] `keySignature.test.ts` sugarlabs/musicblocks-v4-lib#61
- [x] `currentPitch.test.ts`
